### ISSUE TITLE
New user registration

### ISSUE THREAD

**Issue by coliveira4** [CS130-W20/team-A7#1]
## User Story
As a User, I would like to create an account so that I can use the app and store saved data such as my credit card information and saved trips.

## Acceptance Criteria
- [ ] Given user input for email and password , then send to firebase to log as a new account 
- [ ] Given that the new account was created successfully, then log them in automatically.

**Comment by j-011** [comment]
Completed with https://github.com/CS130-W20/team-A7/pull/30
