### ISSUE TITLE
Sign in Existing User

### ISSUE THREAD

**Issue by coliveira4** [CS130-W20/team-A7#2]
## User Story
As a User, I would like to be signed in so that I can access saved trips and check out faster with saved payment information.

## Acceptance Criteria
- [ ] Given credentials from the user, then send credentials to firebase to be authenticated and sign them in if they are.
- [ ] Given the user has recently signed in , then automatically redirect them to the main page

**Comment by j-011** [comment]
Completed with https://github.com/CS130-W20/team-A7/pull/36
