### ISSUE TITLE
Filling in Criteria

### ISSUE THREAD

**Issue by stevenplara** [CS130-W20/team-A7#3]
## User Story
As a User, I would like to fill in my trip criteria so that Serendipity knows what kind of trip I am looking for

## Detailed Description
User will fill in the criteria that will be sent to the Google APIs.

## Acceptance Criteria
- [x] Given form fields, then User will be able to enter information
- [x] Given information, data will be sent to Google APIs

**Comment by j-011** [comment]
Completed with https://github.com/CS130-W20/team-A7/pull/52
