### ISSUE TITLE
Google API communication

### ISSUE THREAD

**Issue by stevenplara** [CS130-W20/team-A7#4]
## User Story
As the Serendipity front-end, I would like to send my trip criteria to Google so that matching flights and hotels will be returned.

## Detailed Description
Google API takes User's trip criteria, provides info of matching criteria, data is sent back to the app to create a trip.

## Acceptance Criteria
- [x] Given the user's completed criteria, then Google APIs will look for matching info
- [x] Given the matching info, the app will receive data from the APIs

**Comment by j-011** [comment]
Completed with https://github.com/CS130-W20/team-A7/pull/58
